gsb_comptable:
    resource: "@GSBComptableBundle/Resources/config/routing.yml"
    prefix:   /

gsb_visiteur:
    resource: "@GSBVisiteurBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
