<?php

namespace GSB\ComptableBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * FicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheFraisRepository extends \Doctrine\ORM\EntityRepository
	{
	public function listerFicheFrais($visiteur){
		// Création du QueryBuilder

		$queryBuilder = $this->_em->createQueryBuilder();
		$queryBuilder->select('v')
		->from ('GSBVisiteurBundle:FicheFrais', 'v')
		->where($queryBuilder->expr()->eq('v.visiteur',':val'))
		->setParameter('val',$visiteur);

		// récupérer la requête
		$query = $queryBuilder->getQuery() ;
		
		// Les résultats
		$resultat = $query->getResult() ;
	
		return $resultat ;

	}
}
